# Generated by Django 4.2.11 on 2024-06-16 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientPassportDetails', models.CharField(blank=True, max_length=50, null=True)),
                ('patientName', models.CharField(blank=True, max_length=50, null=True)),
                ('patientPhone', models.CharField(blank=True, max_length=50, null=True)),
                ('patientAge', models.CharField(blank=True, max_length=50, null=True)),
                ('patientGender', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorLogin', models.CharField(blank=True, max_length=50, null=True)),
                ('doctorMail', models.CharField(blank=True, max_length=50, null=True)),
                ('doctor', models.CharField(choices=[('is_radiologist', 'Рентгенолог'), ('is_gynecologist', 'Гинеколог'), ('is_ophthalmologist', 'Офтальмолог'), ('is_cardiologist', 'Кардиолог'), ('is_procedural_nurse', 'Процедурная медицинская сестра (анализы)'), ('is_mammologist', 'Маммолог'), ('is_urologist', 'Уролог'), ('is_therapist', 'Терапевт')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecordDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathology', models.CharField(default='', max_length=255)),
                ('briefDoctorReport', models.CharField(default='', max_length=255)),
                ('doctorReportWord', models.FileField(default='', upload_to='word_documents/')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
                ('patient_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient_record')),
            ],
        ),
        migrations.AddField(
            model_name='patient_record',
            name='doctors',
            field=models.ManyToManyField(through='main.PatientRecordDoctor', to='main.profile'),
        ),
        migrations.AddField(
            model_name='patient_record',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient'),
        ),
    ]
