# Generated by Django 4.2.11 on 2024-06-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientRecordDoctor',
            new_name='Patient_Record_Doctor',
        ),
    ]
